spring.application.name=API-GATEWAY
server.port=8083

spring.cloud.gateway.server.webmvc.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=OAUTH2
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.server.webmvc.routes[2].id=OAUTH2-CALLBACK
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/login/oauth2/**

spring.cloud.gateway.server.webmvc.default-filters[0]=AddRequestHeader=X-Forwarded-Host,localhost:8083
spring.cloud.gateway.server.webmvc.default-filters[1]=AddRequestHeader=X-Forwarded-Port,8083
spring.cloud.gateway.server.webmvc.default-filters[2]=AddRequestHeader=X-Forwarded-Proto,http

spring.cloud.gateway.server.webmvc.routes[3].id=FLIGHT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/flights/**
#spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1


springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Flight Service
springdoc.swagger-ui.urls[1].url=/flights/v3/api-docs