spring.application.name=API-GATEWAY
server.port=8083

spring.cloud.gateway.server.webmvc.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=OAUTH2
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.server.webmvc.routes[2].id=OAUTH2-CALLBACK
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/login/oauth2/**

spring.cloud.gateway.server.webmvc.default-filters[0]=AddRequestHeader=X-Forwarded-Host,localhost:8083
spring.cloud.gateway.server.webmvc.default-filters[1]=AddRequestHeader=X-Forwarded-Port,8083
spring.cloud.gateway.server.webmvc.default-filters[2]=AddRequestHeader=X-Forwarded-Proto,http

spring.cloud.gateway.server.webmvc.routes[3].id=FLIGHT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/flights/**
#spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[4].id=AIRLINE-AIRPORT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/airline/**,/airport/**

spring.cloud.gateway.server.webmvc.routes[5].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/notifications/**

spring.cloud.gateway.server.webmvc.routes[6].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webmvc.routes[7].id=BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/bookings/**

spring.cloud.gateway.server.webmvc.routes[8].id=PASSENGER-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/passengers/**

spring.cloud.gateway.server.webmvc.routes[9].id=SEAT-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/seats/**

spring.cloud.gateway.server.webmvc.routes[10].id=STRIPE-WEBHOOK
spring.cloud.gateway.server.webmvc.routes[10].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/stripe/webhook

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Flight Service
springdoc.swagger-ui.urls[1].url=/flights/v3/api-docs


spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
