spring.application.name=${SPRING_APPLICATION_NAME:SERVICE-REGISTRY}
server.port=${SERVER_PORT:8761}

#disable as client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.server.port=${MANAGEMENT_PORT:8761}
