spring.application.name=AUTH-SERVICE
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/skyBooker
spring.datasource.username=root
spring.datasource.password=Paarth@29122003

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=my-super-secret-key-my-super-secret-key-12345
jwt.expiration=86400000

server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8083/login/oauth2/code/google

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

registration.secrets.airline-staff=STAFF_SECRET_XYZ_2024
registration.secrets.admin=ADMIN_SECRET_ABC_9999

CLOUDINARY_CLOUD_NAME=dddccxemq
CLOUDINARY_API_KEY=957569861592181
CLOUDINARY_API_SECRET=q1cfgzWBe7ZQaw0eXi1PBYEjBuw