spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

server.forward-headers-strategy=${FORWARD_HEADERS_STRATEGY}

spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

eureka.client.service-url.defaultZone=${EUREKA_SERVER}

registration.secrets.airline-staff=${AIRLINE_STAFF_SECRET}
registration.secrets.admin=${ADMIN_SECRET}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}